stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "aykutsevim/market-rts-oba"

build:
  stage: build
  tags:
    - docker  # Ensure your GitLab Runner is tagged with `docker`
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE:latest .
    - echo "Pushing Docker image..."
    - echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USERNAME --password-stdin
    - docker push $DOCKER_IMAGE:latest
  only:
    - main

deploy:
  stage: deploy
  tags:
    - ssh  # Ensure your GitLab Runner is tagged with `ssh`
  script:
    - echo "Deploying Docker image to target server..."
    - ssh user@target-server "docker pull $DOCKER_IMAGE:latest && docker stop market-rts-oba || true && docker rm market-rts-oba || true && docker run -d --name market-rts-oba -p 80:80 $DOCKER_IMAGE:latest"
  only:
    - main
  #
