#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["MarketWebsocketEndpoint.csproj", "."]
RUN dotnet restore "./MarketWebsocketEndpoint.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "MarketWebsocketEndpoint.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MarketWebsocketEndpoint.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 80
ENTRYPOINT ["dotnet", "MarketWebsocketEndpoint.dll"]
